apiVersion: v1  
kind: Pod
metadata: 
  name: my-app
  labels:
    app: my-app
spec:
  containers: 
    - name: my-app
      image: httpd:latest
      ports:
        - name: httpd:latest
          containerPort: 80